server:
  port: 3344

foo: 1234

spring:
  application:
    name: cloud-eureka-customer
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lxt-jojo/springcloud-config.git #GitHub上面的git仓库名字
          search-paths:  springcloud-config
      label: main
eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为ture
    register-with-eureka: true
    #是否从EurekaServer 抓取已有的注册信息, 默认为true, 单节点无所谓, 集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka7001.com:7001

